# Generated by Django 4.2.1 on 2023-05-20 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productName', models.CharField(max_length=200)),
                ('productInfo', models.TextField(max_length=400)),
                ('productPrice', models.IntegerField()),
            ],
        ),
    ]
