# Generated by Django 4.2.1 on 2023-05-21 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_productimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='productImage',
            field=models.FileField(blank=True, null=True, upload_to='products/'),
        ),
    ]
